Fix build an FreeBSD
... and other BSD as well, hopefully. The build failed in
step 'linking moar', because of:

  ./libmoar.so: undefined reference to 'uv__process_title_cleanup'

dogbert17++ pointed to the changes in
https://github.com/libuv/libuv/commit/72fe3543fe and that we
probably have to adjust our Makefile.