Fix libuv build on Solaris.
This extends the FreeBSD changes of commit 06f041fb08591acd to cover Solaris
too:
    Fix build an FreeBSD

    ... and other BSD as well, hopefully. The build failed in
    step 'linking moar', because of:

      ./libmoar.so: undefined reference to 'uv__process_title_cleanup'