Fix build with gcc 4.8
Build with gcc 4.8 is broken since version 2020.06 and commit
c70587551ab093368e041a65f4a4a8b49d78ce73:

src/debug/debugserver.c: In function 'request_context_lexicals':
src/debug/debugserver.c:1456:9: error: 'for' loop initial declarations are only allowed in C99 mode
         for (MVMuint32 j = 0; j < num_lexicals; j++) {
         ^
Fixes:
 - http://autobuild.buildroot.org/results/179/1799769c531f9f26ff191b1adcd5e5b17dc3b244/build-end.log

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>